# Generated by Django 5.0.7 on 2024-08-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0006_carinventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
